botToken: '7278620564:AAGGm8IJZ_TW8AnXsUNOTT8sMqNw5pmHdI8'
nightscoutUrl: 'https://db349.med-data.online'
chatIds:
  - '5064548184'
language: 'ru'
units: 'mmol/L'

# Available language options:
# en - English
# de - German
# es - Spanish
# zh - Chinese
# ru - Russian
# pt - Portuguese
# fr - French

# Available units options:
# mmol/L - Millimoles per liter
# mg/dL - Milligrams per deciliter
