botToken: 'YOUR_TELEGRAM_BOT_TOKEN'
nightscoutUrl: 'YOUR_NIGHTSCOUT_URL'
chatIds:
  - 'CHAT_ID_1'
  - 'CHAT_ID_2'
language: 'en'
units: 'mmol/L'

# Available language options:
# en - English
# de - German
# es - Spanish
# zh - Chinese
# ru - Russian
# pt - Portuguese
# fr - French

# Available units options:
# mmol/L - Millimoles per liter
# mg/dL - Milligrams per deciliter
